// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqbffoltktgdfmxyrzvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxYmZmb2x0a3RnZGZteHlyenZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTkxNzgsImV4cCI6MjA1OTc5NTE3OH0.DZkRMqoBx30YUZi_73XoolaPGjMt2lwZO7i0FTKCpBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);